// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltmrdbysqurenpeisokk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0bXJkYnlzcXVyZW5wZWlzb2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzUwMjgsImV4cCI6MjA2ODY1MTAyOH0.fcO0BosbSMQuAGHrjbkSIkrruwDZWMlBAbCXgvi8fHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});